import { array } from "prop-types";
import { prisma } from "../src/server/db";
import { Prisma } from "@prisma/client";

const names = [
  "Avram",
  "Antonije",
  "Agnija",
  "Anđelija",
  "Adam",
  "Aran",
  "Aleksandra",
  "Anđelka",
  "Aksentije",
  "Arsenije",
  "Aleksija",
  "Anica",
  "Aleksa",
  "Atanasije",
  "Ana",
  "Anka",
  "Aleksandar",
  "Aćim",
  "Anastasija",
  "Antonina",
  "Alimpije",
  "Aca",
  "Angelina",
  "Anđelko",
  "Aco",
  "Andrijana",
  "Andrija",
  "Anđa",
  "Bane",
  "Borivoje",
  "Biljana",
  "Borka",
  "Blagoje",
  "Borisav",
  "Bisenija",
  "Bosiljka",
  "Blagomir",
  "Borislav",
  "Biserka",
  "Branislava",
  "Blaža",
  "Boško",
  "Blaginja",
  "Branka",
  "Bogdan",
  "Branimir",
  "Blagica",
  "Bratislava",
  "Bogoljub",
  "Bratislav",
  "Blaženka",
  "Bogomir",
  "Branko",
  "Bogdana",
  "Bogosav",
  "Bratoljub",
  "Bogdanka",
  "Borko",
  "Budimir",
  "Božana",
  "Božidar",
  "Budislav",
  "Božidarka",
  "Bojan",
  "Buda",
  "Bojana",
  "Vasilije",
  "Vladislav",
  "Valerija",
  "Višnja",
  "Vekoslav",
  "Vlajko",
  "Varvara",
  "Vladanka",
  "Velibor",
  "Vlastimir",
  "Vasilija",
  "Vlastimirka",
  "Velimir",
  "Vojimir",
  "Veliborka",
  "Vojislava",
  "Velislav",
  "Vojin",
  "Velinka",
  "Vujadinka",
  "Veljko",
  "Vojislav",
  "Vera",
  "Vujka",
  "Veroljub",
  "Vujadin",
  "Verica",
  "Vukadinka",
  "Veselin",
  "Vuk",
  "Verka",
  "Vukica",
  "Vidak",
  "Vukadin",
  "Veronika",
  "Vukosava",
  "Vidoje",
  "Vukajlo",
  "Veroslava",
  "Vuksana",
  "Viktor",
  "Vukan",
  "Veselinka",
  "Vitomir",
  "Vukašin",
  "Vesna",
  "Višeslav",
  "Vukoje",
  "Vidosava",
  "Vladan",
  "Vukosav",
  "Viktorija",
  "Vladeta",
  "Vukota",
  "Violeta",
  "Vladimir",
  "Vuksan",
  "Višeslava",
  "Gavra",
  "Gradimir",
  "Gabrijela",
  "Grozda",
  "Gavrilo",
  "Gradiša",
  "Gaga",
  "Gvozden",
  "Grigorije",
  "Glorija",
  "Georgije",
  "Grozdan",
  "Gordana",
  "Gligorije",
  "Gruja",
  "Gorica",
  "Gojko",
  "Grujica",
  "Goca",
  "Golub",
  "Gradimirka",
  "Goran",
  "Grozdana",
  "David",
  "Dositej",
  "Daliborka",
  "Dragoslava",
  "Dalibor",
  "Dragan",
  "Damjanka",
  "Dubravka",
  "Damjan",
  "Dragiša",
  "Danica",
  "Dunja",
  "Danilo",
  "Drago",
  "Danojlo",
  "Dušanka",
  "Danojlo",
  "Dragoje",
  "Darinka",
  "Dušana",
  "Darko",
  "Dragojlo",
  "Desanka",
  "Dušica",
  "Dejan",
  "Dragoljub",
  "Divna",
  "Desimir",
  "Dragomir",
  "Dobrila",
  "Despot",
  "Drgorad",
  "Dobrinka",
  "Dimitrije",
  "Dragoslav",
  "Dobroslavka",
  "Dmitar",
  "Dragutin",
  "Doris",
  "Dobrašin",
  "Dražo",
  "Doroteja",
  "Dobrivoj",
  "Draško",
  "Dragana",
  "Dobrilo",
  "Dušan",
  "Draginja",
  "Dobrica",
  "Dragica",
  "Dobrosav",
  "Dragojla",
  "Đoka",
  "Đurađ",
  "Đulijana",
  "Đurica",
  "Đokica",
  "Đurđe",
  "Đurđa",
  "Đorđe",
  "Đurica",
  "Đurđija",
  "Đukan",
  "Đuro",
  "Đurđina",
  "Đura",
  "Đurđevka",
  "Emil",
  "Eva",
  "Elena",
  "Emilijan",
  "Egenija",
  "Elizabeta",
  "Evica",
  "Eleonora",
  "Ekatarina",
  "Emilija",
  "Žarko",
  "Živojin",
  "Žaklina",
  "Živkica",
  "Želimir",
  "Živomir",
  "Želimirka",
  "Živodarka",
  "Željko",
  "Živorad",
  "Željka",
  "Živoratka",
  "Živadin",
  "Života",
  "Živadinka",
  "Živoslava",
  "Živan",
  "Žika",
  "Živana",
  "Živoslavka",
  "Živanko",
  "Živanka",
  "Živko",
  "Živka",
  "Zaviša",
  "Zlatoje",
  "Zaga",
  "Zlatomirka",
  "Zdravko",
  "Zlatomir",
  "Zagorka",
  "Zora",
  "Zlatibor",
  "Zlatoslav",
  "Zvezdana",
  "Zorana",
  "Zlatko",
  "Zoran",
  "Zvonka",
  "Zorica",
  "Zdravka",
  "Zorislava",
  "Zlatica",
  "Zorka",
  "Zlata",
  "Ivan",
  "Igor",
  "Ivana",
  "Isidora",
  "Ivica",
  "Ilija",
  "Ivanka",
  "Ivko",
  "Isailo",
  "Ivka",
  "Ivo",
  "Isak",
  "Ivona",
  "Ignjat",
  "Isidor",
  "Ilinka",
  "Ignjatije",
  "Irena",
  "Jagoš",
  "Jovica",
  "Javorka",
  "Jelika",
  "Jakov",
  "Joviša",
  "Jagoda",
  "Jelisaveta",
  "Jakša",
  "Joksim",
  "Jadranka",
  "Jelisavka",
  "Janko",
  "Jordan",
  "Jana",
  "Jelica",
  "Jevrem",
  "Josif",
  "Janovka",
  "Jelka",
  "Jevta",
  "Jugomir",
  "Jasmina",
  "Jefimija",
  "Jezdimir",
  "Jugoslav",
  "Jasminka",
  "Jovana",
  "Jelenko",
  "Julijan",
  "Jasna",
  "Jovanka",
  "Jelisije",
  "Justin",
  "Jevdokija",
  "Jordanka",
  "Jeremije",
  "Jevrosima",
  "Julija",
  "Jerotije",
  "Jela",
  "Julijana",
  "Jovan",
  "Jelena",
  "Julka",
  "Kamenko",
  "Krsman",
  "Kadivka",
  "Kosara",
  "Kirilo",
  "Krsta",
  "Kasija",
  "Kosovka",
  "Kojadin",
  "Krstan",
  "Katarina",
  "Kostadinka",
  "Konstantin",
  "Kristivoje",
  "Katica",
  "Kristina",
  "Kornelije",
  "Kuzman",
  "Kleopatra",
  "Krsmanija",
  "Kosta",
  "Koviljka",
  "Kruna",
  "Kostadin",
  "Kosana",
  "Krunoslava",
  "Laza",
  "Luka",
  "Lara",
  "Lepa",
  "Lazar",
  "Latinka",
  "Leposava",
  "Lale",
  "Lela",
  "Lidija",
  "Leontijr",
  "Lena",
  "Liza",
  "Lepoje",
  "Lenka",
  "Lilijana",
  "Lepomir",
  "Leonida",
  "Lola",
  "Lola",
  "Leonora",
  "Lucija",
  "Ljuba",
  "Ljubo",
  "Ljeposava",
  "Ljubinka",
  "Ljuban",
  "Ljubomir",
  "Ljilja",
  "Ljubomirka",
  "Ljubivoje",
  "Ljupče",
  "Ljiljana",
  "Ljupka",
  "Ljubinko",
  "Ljuba",
  "Ljubiša",
  "Ljubica",
  "Makarije",
  "Milojko",
  "Magdalena",
  "Maksim",
  "Milorad",
  "Makrena",
  "Manojlo",
  "Miloš",
  "Malina",
  "Marijan",
  "Milun",
  "Margareta",
  "Marinko",
  "Milutin",
  "Marija",
  "Marjan",
  "Miodrag",
  "Mašinka",
  "Marko",
  "Miomir",
  "Melenija",
  "Mateja",
  "Mirko",
  "Mila",
  "Matija",
  "Miroljub",
  "Miladinka",
  "Melentije",
  "Miroslav",
  "Mileva",
  "Metodije",
  "Mitar",
  "Milena",
  "Mijalko",
  "Mihailo",
  "Milenija",
  "Mijat",
  "Mladen",
  "Milesa",
  "Miladin",
  "Mladomir",
  "Milijana",
  "Milan",
  "Mojsilo",
  "Milica",
  "Milanko",
  "Momir",
  "Milka",
  "Milentije",
  "Momcilo",
  "Milojka",
  "Mileta",
  "Moša",
  "Milja",
  "Milivoj",
  "Mirjana",
  "Milija",
  "Mira",
  "Milijan",
  "Miroslava",
  "Milinko",
  "Mirosava",
  "Milisav",
  "Mitra",
  "Milovan",
  "Miloje",
  "Najdan",
  "Neško",
  "Nada",
  "Ninoslava",
  "Naum",
  "Nikola",
  "Nadežda",
  "Nina",
  "Nebojša",
  "Ninko",
  "Nastasija",
  "Novka",
  "Negovan",
  "Ninoslav",
  "Natalija",
  "Negomir",
  "Nićifor",
  "Nevena",
  "Negoslav",
  "Novak",
  "Nevenka",
  "Nedeljko",
  "Novica",
  "Negosava",
  "Nemanja",
  "Novko",
  "Nedeljka",
  "Nenad",
  "Nikolija",
  "NJ",
  "NJ",
  "Njegovan",
  "Njegoslav",
  "Njegosava",
  "Njegoje",
  "Njegoš",
  "Njegoslava",
  "Njegomir",
  "Njeguš",
  "Njegosav",
  "Obrad",
  "Ozren",
  "Obradinka",
  "Olgica",
  "Obradin",
  "Oliver",
  "Obrenija",
  "Olivera",
  "Obren",
  "Ostoja",
  "Ozrenka",
  "Oliverka",
  "Ognjen",
  "Olga",
  "Olja",
  "Ozarija",
  "Pavle",
  "Prodan",
  "Pava",
  "Petra",
  "Pantelija",
  "Prokopije",
  "Pavlija",
  "Petrija",
  "Paun",
  "Prohor",
  "Pajka",
  "Petruška",
  "Peran",
  "Puniša",
  "Pauna",
  "Podgorka",
  "Petar",
  "Puriša",
  "Pelagija",
  "Poleksija",
  "Petko",
  "Peladija",
  "Prvoslava",
  "Petronije",
  "Perka",
  "Prvoslavka",
  "Prvoslav",
  "Persa",
  "Prodana",
  "Predrag",
  "Persida",
  "Poljka",
  "Prerad",
  "Perunika",
  "Radan",
  "Ranđel",
  "Radenka",
  "Radenko",
  "Ranisav",
  "Radivojka",
  "Radivoj",
  "Ranko",
  "Radinka",
  "Radivoje",
  "Ratislav",
  "Radmila",
  "Radisav",
  "Rastko",
  "Radojka",
  "Radiša",
  "Ratibor",
  "Radojla",
  "Radmilo",
  "Ratimir",
  "Radomirka",
  "Radovan",
  "Ratko",
  "Radoslava",
  "Radoje",
  "Ratomir",
  "Radoslavka",
  "Radojica",
  "Rafailo",
  "Razumenka",
  "Radojko",
  "Raško",
  "Ranka",
  "Radojlo",
  "Relja",
  "Ranđa",
  "Radoljub",
  "Ristivoj",
  "Ranka",
  "Radoman",
  "Ristivoje",
  "Ratiborka",
  "Radomir",
  "Rodoljub",
  "Ratka",
  "Radonja",
  "Roksanda",
  "Radosav",
  "Ruža",
  "Radoslav",
  "Ružica",
  "Radoš",
  "Ruzmirka",
  "Radul",
  "Rumenka",
  "Radule",
  "Rajica",
  "Rajko",
  "Sava",
  "Srđan",
  "Sava",
  "Sonja",
  "Svetislav",
  "Sredoje",
  "Saveta",
  "Sofija",
  "Svetozar",
  "Sreten",
  "Savka",
  "Spasenija",
  "Svetoje",
  "Sretoje",
  "Sajka",
  "Spomenka",
  "Svetolik",
  "Srećko",
  "Sandra",
  "Srbijanka",
  "Svetomir",
  "Srpko",
  "Sanja",
  "Srbislava",
  "Sekula",
  "Stavra",
  "Sara",
  "Sretenka",
  "Selimir",
  "Stamenko",
  "Svetislava",
  "Stojka",
  "Sergije",
  "Stanimir",
  "Svetislavka",
  "Stamena",
  "Sibin",
  "Stanislav",
  "Svetlana",
  "Stamenija",
  "Sima",
  "Staniša",
  "Selena",
  "Stamenka",
  "Simeon",
  "Stanko",
  "Sibinka",
  "Stana",
  "Siniša",
  "Stanoje",
  "Simeuna",
  "Stanija",
  "Slaven",
  "Stanojlo",
  "Simka",
  "Stanika",
  "Slavenko",
  "Steva",
  "Simona",
  "Stanislava",
  "Slaviša",
  "Stevan",
  "Simonida",
  "Stanica",
  "Slavko",
  "Stepan",
  "Sin",
  "Stanka",
  "Slavoljub",
  "Stefan",
  "Slavenka",
  "Stanojka",
  "Slobodan",
  "Stojadin",
  "Slavica",
  "Stanojla",
  "Sotir",
  "Stojan",
  "Slavka",
  "Stevanija",
  "Sofronije",
  "Stojiljko",
  "Slavna",
  "Stevka",
  "Spasoje",
  "Stojko",
  "Slobodanka",
  "Stoja",
  "Spira",
  "Stojmen",
  "Smilja",
  "Stojadinka",
  "Spridon",
  "Stokan",
  "Smiljana",
  "Stojana",
  "Spomenko",
  "Stole",
  "Snežana",
  "Stojanka",
  "Srba",
  "Strajin",
  "Soja",
  "Stojka",
  "Srbislav",
  "Strahinja",
  "Sojka",
  "Stojna",
  "Srboljub",
  "Stracimir",
  "Soka",
  "Suzana",
  "Suncica",
  "Tadija",
  "Toma",
  "Tada",
  "Tanasije",
  "Tomislav",
  "Tamara",
  "Tanasko",
  "Toplica",
  "Takosava",
  "Tatomir",
  "Toša",
  "Tanja",
  "Taško",
  "Trajan",
  "Tatjana",
  "Teodor",
  "Trajko",
  "Teodora",
  "Teodosije",
  "Trivun",
  "Tijana",
  "Teofan",
  "Trifun",
  "Tina",
  "Teohar",
  "Tugomir",
  "Todora",
  "Tešman",
  "Tomanija",
  "Timotije",
  "Tomka",
  "Tiosav",
  "Trajanka",
  "Tihomir",
  "Toda",
  "Todor",
  "Ćetko",
  "Ćirilo",
  "Ćana",
  "Ćirka",
  "Ćile",
  "Ćira",
  "Ćanka",
  "Ćuba",
  "Uglješa",
  "Uranko",
  "Ubavka",
  "Ugren",
  "Uroš",
  "Una",
  "Fedor",
  "Filotej",
  "Fanija",
  "Feodor",
  "Fotije",
  "Fema",
  "Filip",
  "Filipa",
  "Filiman",
  "Filipinka",
  "Hariton",
  "Hristivoj",
  "Helena",
  "Hranislavka",
  "Hranislav",
  "Hristivoje",
  "Hranislava",
  "Hristina",
  "Cane",
  "Cvijan",
  "Caja",
  "Cveta",
  "Cvetin",
  "Cvijetin",
  "Cajka",
  "Cvetana",
  "Cvetko",
  "Cvijo",
  "Caka",
  "Cvetanka",
  "Cvetomir",
  "Cviko",
  "Cana",
  "Ceca",
  "Časlav",
  "Čedomir",
  "Časlavka",
  "Čeda",
  "Čubrilo",
  "Čedomirka",
  "Šako",
  "Šiško",
  "Šana",
];
function makelen13(jmbg: number) {
  let jmbgString = jmbg > 100 ? jmbg.toString() : "99";
  const jmbgLength = jmbgString.length;

  if (jmbgLength > 13) {
    return Number(jmbgString.slice(0, 12));
  } else if (jmbgLength < 13) {
    return Number(jmbgString.padEnd(12, "0"));
  } else {
    return jmbg;
  }
}
async function main() {
  const id = "cl9ebqhxk00003b600tymydho";

  const tipLekata = ["DOKTOR", "HIRURG", "MEDICINSKI_RADNIK", "NE_MEDICINSKO"];

  let ordinacije = [];
  for (let i = 0; i < 100; i++) {
    const temp1: Prisma.OrdinacijaCreateManyInput = {
      id: "sob" + Math.floor(Math.random() * 10000),
      brojSobe: "br" + Math.floor(Math.random() * 1000),
      imeOrdinacija: "Kardiologija",
      kapacitet: Math.floor(Math.random() * 100),
      telefon: "+381-" + Math.floor(100 * (Math.random() * 10)),
    };
    ordinacije.push(temp1);
  }

  let osoblje = [];
  for (let index = 0; index < ordinacije.length; index++) {
    const element = ordinacije[index];

    osoblje.push(
      {
        ime: names[Math.floor(Math.random() * names.length)] + " ",
        prezime: names[Math.floor(Math.random() * names.length)] + " ",
        kontakt: "+381-" + Math.floor(100 * (Math.random() * 10)),
        tipOsoblja: "DOKTOR",
        // @ts-ignore
        ordinacijaId: element?.id,
      },
      {
        ime: names[Math.floor(Math.random() * names.length)] + " ",
        prezime: names[Math.floor(Math.random() * names.length)] + " ",
        kontakt: "+381-" + Math.floor(100 * (Math.random() * 10)),
        tipOsoblja: "DOKTOR",
        // @ts-ignore
        ordinacijaId: element?.id,
      },
      {
        ime: names[Math.floor(Math.random() * names.length)] + " ",
        prezime: names[Math.floor(Math.random() * names.length)] + " ",
        kontakt: "+381-" + Math.floor(100 * (Math.random() * 10)),
        tipOsoblja: "DOKTOR",
        // @ts-ignore
        ordinacijaId: element?.id,
      }
    );
  }

  let pacijenti: Prisma.PacijentUncheckedCreateInput[] = [];
  for (let index = 0; index < names.length; index++) {
    const ranNum = Math.floor(Math.random() * names.length);

    const pac: Prisma.PacijentUncheckedCreateInput = {
      datumRodj: new Date(Date.now() - Math.random() * 10000),
      ime: names[ranNum] + " ",
      prezime: names[Math.random() * names.length] + "vić",
      jmbg: makelen13(Math.floor(100000000000 * (Math.random() * 10))),
      lbo: "lbo" + 100000000000 * (Math.random() * 10),
    };

    pacijenti.push(pac);
  }
  let aktivnePosete: Prisma.PosetaUncheckedCreateInput[] = [];
  for (let index = 0; index < 100; index++) {
    aktivnePosete.push({
      simptomi: "Glavobolja",
      prioritet: 0,

      pacijentJMBG:
        // @ts-ignore
        pacijenti[Math.floor(Math.random() * pacijenti.length)].jmbg,
      id: "pos" + Math.floor(Math.random() * 10000),
    });
  }

  let pregledi: Prisma.PregledUncheckedCreateInput[] = [];
  for (let index = 0; index < 100; index++) {
    pregledi.push({
      // @ts-ignore
      ordinacijaId:
        // @ts-ignore
        ordinacije[Math.floor(Math.random() * ordinacije.length)].id,
      // @ts-ignore
      posetaId:
        // @ts-ignore
        aktivnePosete[Math.floor(Math.random() * aktivnePosete.length)].id,
    });
  }

  let gotovePosete: Prisma.PosetaUncheckedCreateInput[] = [];

  for (let index = 0; index < 100; index++) {
    gotovePosete.push({
      simptomi: "Glavobolja",
      prioritet: 0,
      dolazak: new Date(Date.now() - Math.random() * 10000),
      odlazak: new Date(Date.now() - Math.random() * 10000),
      gotova: true,
      uput: "uput" + Math.floor(Math.random() * 10000),
      pacijentJMBG:
        // @ts-ignore
        pacijenti[Math.floor(Math.random() * pacijenti.length)].jmbg,
      id: "pos" + Math.floor(Math.random() * 10000),
    });
  }
  for (let index = 0; index < 100; index++) {
    pregledi.push({
      // @ts-ignore
      ordinacijaId:
        // @ts-ignore
        ordinacije[Math.floor(Math.random() * ordinacije.length)].id,
      // @ts-ignore
      posetaId:
        // @ts-ignore
        gotovePosete[Math.floor(Math.random() * gotovePosete.length)].id,
    });
  }

  await prisma.$transaction([
    prisma.osoblje.createMany({
      //@ts-ignore
      data: osoblje,
      skipDuplicates: true,
    }),
    prisma.pacijent.createMany({
      data: pacijenti,
      skipDuplicates: true,
    }),
    prisma.poseta.createMany({
      data: aktivnePosete,
      skipDuplicates: true,
    }),
    prisma.poseta.createMany({
      data: gotovePosete,
      skipDuplicates: true,
    }),
    prisma.pregled.createMany({
      data: pregledi,
      skipDuplicates: true,
    }),
    prisma.ordinacija.createMany({
      data: ordinacije,
      skipDuplicates: true,
    }),
  ]);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
