import Table from "@/components/Table";
import MainLayout from "@/layouts/MainLayout";
import { RouterOutputs, api } from "@/utils/api";
import { createColumnHelper, getCoreRowModel } from "@tanstack/react-table";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Page({}) {
  const router = useRouter();
  const posetaData = api.poseta.getOne.useQuery(router.query.id as string);

  if (!posetaData.data) return <div>Loading...</div>;

  const data = posetaData.data;
  const { dolazak, gotova, odlazak, pregledi, prioritet, pacijent } = data;
  const { ime, prezime, jmbg } = pacijent;

  return (
    <MainLayout>
      <Head>
        <title>Poseta - {data?.pacijent.ime}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col  p-4">
        <div className="grid  grid-cols-[3fr_2fr] items-center justify-center">
          <div>
            <h2 className="text-lg font-medium text-gray-800  ">Sok Soba</h2>

            <p className="mt-1 text-sm text-gray-500  "></p>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex flex-col rounded-xl bg-white p-4">
            <h2 className="text-lg font-medium text-gray-800  ">Pacijent</h2>
            <span className=""> Ime: {ime}</span>
            <span className=""> Prezime: {prezime}</span>
            <span className=""> JMBG: {jmbg.toString()}</span>
          </div>
          {prioritet > 0 && (
            <div className="flex flex-col items-center justify-center rounded-xl bg-red-600 p-4">
              <span className=""> Prioritet: {prioritet}</span>
            </div>
          )}
          <div className="col-start-2 flex flex-col rounded-xl bg-white p-4">
            <h2 className="text-lg font-medium text-gray-800  ">Poseta</h2>
            <span className=""> Dolazak: {dolazak.toLocaleDateString()}</span>
            <span className=""> Odlazak: {odlazak?.toLocaleDateString()}</span>
            <span className=""> Gotova: {gotova ? "Da" : "Ne"}</span>
            <span className=""> Prioritet: {prioritet}</span>
          </div>
        </div>
      </main>
    </MainLayout>
  );
}
