import Table from "@/components/Table";
import MainLayout from "@/layouts/MainLayout";
import { RouterOutputs, api } from "@/utils/api";
import { createColumnHelper, getCoreRowModel } from "@tanstack/react-table";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Page() {
  const router = useRouter();
  const { id } = router.query as { id: string };

  return (
    <MainLayout>
      <main className="container flex flex-col  p-4">
        <div className="grid  grid-cols-[3fr_2fr] items-center justify-center">
          <div>
            <h2 className="text-lg font-medium text-gray-800  ">Ordinacije</h2>
            <p className="mt-1 text-sm text-gray-500  "></p>
          </div>
        </div>
        <div className="flex flex-col gap-8">
          <Layout id={id}></Layout>
        </div>
      </main>
    </MainLayout>
  );
}

type Osoblje = Exclude<RouterOutputs["osoblje"]["getOne"], null>;

function Layout({ id }: { id: string }) {
  const { data } = api.osoblje.getOne.useQuery(id);

  if (!data) return <div>Loading...</div>;

  const { ime, kontakt, ordinacijaId, prezime, tipOsoblja } = data;
  return (
    <>
      <Head>
        <title>Osoblje - {id}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-4 rounded-xl bg-white p-4 ">
        <h2 className="text-lg font-medium text-gray-800  ">
          Osoblje - {id && id}
        </h2>
        <span>Ime: {ime} </span>
        <span>Prezime: {prezime} </span>
        <span>Kontakt: {kontakt} </span>
        <span>Tip Osoblja: {tipOsoblja} </span>
        <Link href={`/ordinacija/${ordinacijaId}`}>
          Ordinacija Id: {ordinacijaId}{" "}
        </Link>
      </div>
    </>
  );
}
